# Basic Information
title: "Sepehr Khodadadi"
position: "M.Sc. Student in Data Science and Engineering (AI track)"
affiliation: "MaLGa (Machine Learning Genoa Center), University of Genoa"
affiliation_link: "https://malga.unige.it/"
email: "thisissepehrkhd (at) gmail.com"

# Search Engine Optimization (SEO)
keywords: "Sepehr Khodadadi, machine unlearning, trustworthy machine learning, data privacy, University of Genoa, MaLGa"
description: "Sepehr Khodadadi, M.Sc. student at the University of Genoa working on machine unlearning and trustworthy machine learning at MaLGa, in collaboration with Télécom Paris."
canonical: "https://sepehrkdi.github.io/"

# Links
google_scholar: "https://scholar.google.com/citations?user=bhDhM8MAAAAJ"
cv_link: ./assets/files/CV_Sepehr_Khodadadi.pdf
github_link: "https://github.com/sepehrkdi"
linkedin: "https://linkedin.com/in/sepehr-khodadadi"

# Images
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor
